### ISSUE TITLE
Total views counts

### ISSUE THREAD

**Issue by ogencoglu** [petermeissner/wikipediatrend#24]
Can total view counts (sum of all pages) for a language for a certain period be extracted? This is quite important for normalizing the counts of a page through time.

**Comment by petermeissner** [comment]
Not that I know of - so far. Maybe I will look into it some more. So far I used the counts for "Main_Page" as proxy for overall page usage. If you stumble upon it I would build it in for easy use.

**Comment by petermeissner** [comment]
OK, it should be somewhere in the Wikipedia API ... I will put it in ... I cannot promise when though.

**Comment by ogencoglu** [comment]
OK thanks.

**Comment by petermeissner** [comment]
I investigated this a little bit more and found nothing in the API, there is nothing on stats.grok.se and transforming and aggregating the raw data into daily counts resisted my attempts in two ways: it is quite big 2 GB for 2008 to 2015 and it seems to need some (serious) cleansing to get it right. 

So, I will not attempt to include daily overall Wikipedia access counts as long as their is no API or reliable/updating source for that. 

The raw data for hourly project access is accessible here: http://dumps.wikimedia.org/other/pagecounts-ez/projectcounts/
