### ISSUE TITLE
Same issue #17 but with higher versions

### ISSUE THREAD

**Issue by agiani99** [petermeissner/wikipediatrend#25]
Hi Peter
with following sessionInfo

```r 
sessionInfo()
## R version 3.2.3 (2015-12-10)
## Platform: i386-w64-mingw32/i386 (32-bit)
## Running under: Windows 7 x64 (build 7601) Service Pack 1

## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
## [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     

## other attached packages:
## [1] rvest_0.3.1          xml2_0.1.2           jsonlite_0.9.19      AnomalyDetection_1.0 wikipediatrend_1.1.7
## [6] Rcpp_0.12.3          nlme_3.1-124         ggplot2_2.0.0       

## loaded via a namespace (and not attached):
##  [1] lattice_0.20-33  digest_0.6.9     bitops_1.0-6     R6_2.1.2         grid_3.2.3       plyr_1.8.3      
##  [7] gtable_0.1.2     magrittr_1.5     scales_0.3.0     httr_1.1.0       stringi_1.0-1    curl_0.9.6      
## [13] labeling_0.3     tools_3.2.3      stringr_1.0.0    RCurl_1.95-4.7   munsell_0.4.3    colorspace_1.2-6
```

I got the same problem of issue #17 

```r
Warning message:
In value[[3L]](cond) : [wp_jsons_to_df()]
Could not extract data from server response. Data for one month will be missing.
```

What can be wrong? No packages installed from github.

**Comment by petermeissner** [comment]
What is the actual line of code that you try to run?

**Comment by agiani99** [comment]
Oops, sorry

library(Rcpp)
library(wikipediatrend)
library(AnomalyDetection)
library(ggplot2)
library(jsonlite)
library(rvest)
test <- "Lidocaine"
ed_data = wp_trend(test, from="2013-01-31", to=prev_month_end(), lang = "en")

**Comment by petermeissner** [comment]
Hmmm, 
I cannot replicate the reported behavior. I have tested on Linux with 64bit version but otherwise have the same specifications with the same lines of code as you have: 

```r
sessionInfo()
## R version 3.2.3 (2015-12-10)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 14.04.4 LTS

## locale:
##  [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
##  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
##  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     

## other attached packages:
## [1] rvest_0.3.1                 xml2_0.1.2                 
## [3] jsonlite_0.9.19             ggplot2_2.0.0              
## [5] AnomalyDetection_1.0        wikipediatrend_1.1.8.900000
## [7] Rcpp_0.12.3                

## loaded via a namespace (and not attached):
##  [1] bitops_1.0-6      grid_3.2.3        plyr_1.8.3        R6_2.1.2         
##  [5] gtable_0.1.2      magrittr_1.5      scales_0.3.0      httr_1.1.0       
##  [9] stringi_1.0-1     curl_0.9.6        hellno_0.0.2.9000 tools_3.2.3      
## [13] stringr_1.0.0     RCurl_1.95-4.7    munsell_0.4.3     colorspace_1.2-6 
```

The error that you report does indicate that something went wrong in the attempt to parse the data returned by the server. This might be due to:

- some bug in the package
- server errors
- errors in the data provided by the server

Do your lines of code maybe run through now? My guess is, that the server **temporarily** did return bad data or not data at all.

**Comment by agiani99** [comment]
Yep. Today it works. Sorry for time waste. thx.

**Comment by petermeissner** [comment]
Nah, thanks for reporting. Maybe I should make the error statement more informative.

**Comment by agiani99** [comment]
Hi Peter, just a curiosity: do you know other public sites which offers similar stat service like stats.grok.se?
Best

**Comment by petermeissner** [comment]
Have a look at the pageviews package by Oliver Keys. It uses another data source. It is on my ToDo for wikipediatrend to use that source as well but I will not be able to do it before second week of March this year.

**Comment by agiani99** [comment]
Thanks Peter.
Have a look to anomaly detection package as well if you think to go in this direction. I am deeply convinced that API client like yours plus basic descriptive statistic can do amazing thing not yet surfaced....
Thanks for your help. Much appreciated.
Andrea
