### ISSUE TITLE
Feature Request :datasource

### ISSUE THREAD

**Issue by rt711** [petermeissner/wikipediatrend#29]
Could you please add [this](https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user) additional datasource ?
There is a way to download CSV directly, so no JSON to CSV is required in R.

**Comment by petermeissner** [comment]
see here: https://github.com/Ironholds/pageviews/issues/9

**Comment by petermeissner** [comment]
Furthermore, I just now started a statsgrokse package which means I finally get myself to allocate time to restructure wikipediatrend into a API binding package for stats.grok.se and a wrapper package. When this is done, the next step is to include the pageviews package as a second and recent data source.

I think this could be done by the end March.

**Comment by petermeissner** [comment]
From Version 2.x.x wikipediatrend uses the new API as data source (which provides data from mid 2015 onwards).
