### ISSUE TITLE
Does pageviews replace wikipediatrend?

### ISSUE THREAD

**Issue by masalmon** [petermeissner/wikipediatrend#30]
The [`pageviews` package](https://github.com/ironholds/pageviews) was brought to my attention.

Does `wikipediatrend` rely on deprecated datasets? https://twitter.com/bearloga/status/836936937743097856

In any case, thanks for your work for this package :-)

**Comment by petermeissner** [comment]
no, see here for discussion: https://github.com/Ironholds/pageviews/issues/9 and the plan .... 
see here for the first steps to accomplish the plan: https://github.com/petermeissner/statsgrokse ... 
and also here: https://github.com/petermeissner/wikipediatrend/issues/29

😀
