### ISSUE TITLE
The wikipediatrend package currently has no server providing any page view information.  Use package pageviews for recent (2016+) information.  Older information hopefully available again soon.

### ISSUE THREAD

**Issue by Lalemadahali** [petermeissner/wikipediatrend#32]
While using this package I get this error.
"The wikipediatrend package currently has no server providing any page view information. 
Use package pageviews for recent (2016+) information. 
Older information hopefully available again soon."

**Comment by petermeissner** [comment]
Could you please provide the output of a call to `sessionInfo()` when the package is loaded. Are you sure that you have the latest version of the package installed?

In general there is a known issue: some time ago stats.grok.se provided data reaching back until late 2007. This server went out of office. Wikipedia folks started a new service but it only offers data from late 2015 onwards. 

I poked at the Wikipedia folks but there is no real timeline when or if this might get available. I tried to extract the data myself but this is HUGE -- really huge, really ugly!

To get an update or simply to poke at those who might be able to get this stuff going register here and write to the list: https://lists.wikimedia.org/mailman/listinfo/analytics

The actual raw data files can be obtained here: https://dumps.wikimedia.org/other/pagecounts-raw/ in case somebody wants to try it here- or himself. 

😭

**Comment by MoritzLaurer** [comment]
Hi Peter, 

the package is a really great idea and I would love to use it! Unfortunately, I get the same error message as Lalemadahali. 

I tried these two calls: 
weber <- wp_trend(Manfred_Weber, from = "2007-01-01",
                  to = "2017-01-01", lang = "en") 

and the one from your readme: 
trend_data <- 
  wp_trend(
    page = c("Der_Spiegel", "Die_Zeit"), 
    lang = c("de", "en"), 
    from = "2007-01-01",
    to   = "2017-01-01")

But I always get this error message: 
"The wikipediatrend package currently has no server providing any page view information. 
Use package pageviews for recent (2016+) information. 
Older information hopefully available again soon."

I installed the latest CRAN version with install.packages("wikipediatrends") today. 
Here is the output you asked for: 
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] wikipediatrend_1.1.14

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    yaml_2.2.0    
[4] hellno_0.0.1

**Comment by petermeissner** [comment]
Terrabytes of data have been munged ...
... wikipediatrend is back online.
