### ISSUE TITLE
Error in order(res$date) : argument 1 is not a vector

### ISSUE THREAD

**Issue by saschagobel** [petermeissner/wikipediatrend#38]
For some Wikipedia pages I receive the following error message when setting the `from` argument to a date before 2016-01-01. For instance:

```
trend_data <- wp_trend(
    page = "Anton_von_Aretin_(Politiker)", 
    lang = c("de"), 
    from = "2007-01-01",
    to   = Sys.Date()
  )
Error in order(res$date) : argument 1 is not a vector
```

or

```
trend_data <- 
  wp_trend(
    page = "Hana_Kordová_Marvanová", 
    lang = c("cs"), 
    from = "2007-01-01",
    to   = Sys.Date()
  )
Error in order(res$date) : argument 1 is not a vector
```

The respective Wikipedia pages exist and carry the same title:
https://de.wikipedia.org/wiki/Anton_von_Aretin_(Politiker)
https://cs.wikipedia.org/wiki/Hana_Kordov%C3%A1_Marvanov%C3%A1

This can be resolved by setting the `from` argument to 2016-01-01 or later, i.e., using the pageviews API. However, both Wikipedia pages existed before that date.

**Comment by petermeissner** [comment]
- Confirmed
- This seems to happen when no old data is available
- should be fixed
