### ISSUE TITLE
Timeout error, cannot execute any wp_trend command

### ISSUE THREAD

**Issue by d-qn** [petermeissner/wikipediatrend#39]
Hello,

I am not able to get any wp_trend results, the timeout error is always the same. Example:

`res <- wp_trend(page=c("Der_Spiegel", "Die_Zeit"), lang=c("de", "en"))`

yields

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached: [petermeissner.de:8880] Connection timed out after 10002 milliseconds

I am using R 3.5.1 on macOS  10.15.2, wikipediatrend_2.1.4

Thank you in advance!

**Comment by petermeissner** [comment]
Hmmm, Service seems to work in general.

Can you post the output of `sessionInfo()`?

**Comment by d-qn** [comment]
You are right, false alarm it was a network setup issue. I tired with different wifi and LAN connections and it worked.
