### ISSUE TITLE
Gathering total pageviews for a language project using wikipediatrends

### ISSUE THREAD

**Issue by bwilker** [petermeissner/wikipediatrend#40]
Is it possible to gather total pageviews for a language project using wikipediatrends? 

Great package.

**Comment by petermeissner** [comment]
Theoretical, yes. But currently there is no way to get the numbers in any practical way.

Outside the package these number exist, e.g.: https://stats.wikimedia.org/EN/TablesPageViewsMonthly.htm

**Comment by petermeissner** [comment]
out of scope-ish / open for pull requests
