### ISSUE TITLE
Wikipedia Page Views Error

### ISSUE THREAD

**Issue by ald0405** [petermeissner/wikipediatrend#42]
```
library(wikipediatrend)
data <- wp_trend(page = 'cera_care',
                  from = '2017-01-01',
                  to = Sys.Date())
```

Warning in value[[3L]](cond) :
  Unable to retrieve data via {pageviews}.
Error: The date(s) you used are valid, but we either do not have data for those date(s), or the project you asked for is not loaded yet.  Please check https://wikimedia.org/api/rest_v1/?doc for more information.. Params: project = 'en', article='Cera_care', start='2017010100', end='2020041800', user_type='all', platform='all'.
Error in order(res$date, res$language, res$article) : 
  argument 1 is not a vector

**Comment by petermeissner** [comment]
Please consider taking more care in posting your problem:

- e.g https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/
- read this: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/16532098
- e.g. have a look at the {reprex} package 


Have a close look at your error message...

```
Error: The date(s) you used are valid, but we either do not have data for 
those date(s), or the project you asked for is not loaded yet. [...]
```

...and the exact title of the article: https://en.wikipedia.org/wiki/Cera_Care

If you carefully replicate the article's casing, things work - can you spot the difference to your code?!:

```
library(wikipediatrend)
data <- wp_trend(page = 'Cera_Care',  from = '2017-01-01',  to = Sys.Date())

data
##    language article   date       views
## 1  en       cera_care 2020-03-23  43  
## 2  en       cera_care 2020-03-24  43  
## 3  en       cera_care 2020-03-25  64  
## 4  en       cera_care 2020-03-26  65  
## 5  en       cera_care 2020-03-27  45  
## 22 en       cera_care 2020-04-13  81  
## 23 en       cera_care 2020-04-14  25  
## 24 en       cera_care 2020-04-15  43  
## 25 en       cera_care 2020-04-16 310  
## 26 en       cera_care 2020-04-17  38  
## 
## ... 16 rows of data not shown
```
