### ISSUE TITLE
Wikipedia trend and jump in counts in January 2016

### ISSUE THREAD

**Issue by JacopoCerri** [petermeissner/wikipediatrend#43]
Dear  all,

I am a postdoc, who is using the "wikipediatrend" package to conduct time series analysis of wikipedia views. I noticed that data extracted with this package experience a jump in January 2016, at least when observations come from it.wikipedia.org. This jump is widespread across all the pages from it.wikipedia.org.
An example with three different searches ("alien species", "beer", "democracy"):

![image](https://user-images.githubusercontent.com/42981212/80910679-7e4b4f00-8d31-11ea-9d61-4932c183e2cf.png)

I do not understand why this change occurs. Maybe something changed in the way Wikipedia recorded the visits to the various pages, in 2016? For example, maybe it did not record searches from mobile until December 2015.

Kind regards,

Jacopo Cerri

**Comment by petermeissner** [comment]
Your observation is precisely what's going on: The data provided by the package consists of two different data sources one before 2016 and one after. 

More information on that matter can be found here: 

- https://dumps.wikimedia.org/other/analytics/
- https://dumps.wikimedia.org/other/pageviews/readme.html
- https://meta.wikimedia.org/wiki/Research:Page_view

On this page you can find the raw files that are the basis for the data from between 2007 and 2015: https://dumps.wikimedia.org/other/pagecounts-raw/ those files were filtered to only contain pageviews for requests to Wikipedia pages (not Wiktionary and other Wiki pages). 

All source code for the extraction can be found here, although it will not make sense on first sight: https://github.com/petermeissner/wpd. 

Checking the code as well as the documentation of the file format again (https://dumps.wikimedia.org/other/pagecounts-raw/), I say that numbers before 2016 do not entail any requests to any of those 'special pages': 

![image](https://user-images.githubusercontent.com/939139/80926264-75d92f80-8d96-11ea-93ec-219664db51bd.png)

... which excludes mobile as well.
